[versions]
checkstyle = "10.12.4"
spotbugs = "4.9.8"
pmd = "7.18.0"
jacoco = "0.8.9"
vertx = "4.5.14"

[libraries]
junit-platform = "org.junit:junit-bom:6.0.0"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }
pmd-java = { module = "net.sourceforge.pmd:pmd-java", version.ref = "pmd" }
pmd-ant = { module = "net.sourceforge.pmd:pmd-ant", version.ref = "pmd" }
apache-commons-cli = "commons-cli:commons-cli:1.10.0"
vertx-core = { module = "io.vertx:vertx-core", version.ref = "vertx" }
vertx-sync = { module = "io.vertx:vertx-sync", version.ref = "vertx" }
vertx-web = { module = "io.vertx:vertx-web", version.ref = "vertx" }
vertx-web-client = { module ="io.vertx:vertx-web-client", version.ref = "vertx" }
jackson-core = "com.fasterxml.jackson.core:jackson-databind:2.20.1"

[plugins]
shadowJar = "com.github.johnrengelman.shadow:8.1.1"
spotbugs = "com.github.spotbugs:6.4.4"
docker = "com.bmuschko.docker-remote-api:10.0.0"
sonarqube =  "org.sonarqube:7.0.1.6134"
